module.exports = {
  main: [
    {
      type: 'doc',
      label: 'Introduction',
      id: 'README',
    },
    {
      type: 'category',
      label: 'Nest CLI',
      items: [{ type: 'autogenerated', dirName: 'cli' }],
    },
    {
      type: 'category',
      label: 'Eggs',
      items: [{ type: 'autogenerated', dirName: 'eggs' }],
    },
    {
      type: 'category',
      label: 'REST API',
      items: [{ type: 'autogenerated', dirName: 'api' }],
    },
  ],
};
